(defun server ()
    (let ((socket (socket-server 4010))) ;tcp/4010でソケット
    (unwind-protect 
        (loop (with-open-stream (stream (socket-accept socket))
            (parse-method-path (read-line stream))
            (format stream (concatenate 'string (create-http-header) (get-packet-html))))
    ) (socket-server-close socket))))


(defun parse-method-path (str) 
    (let ((method (subseq str  0 (position #\space str))) ;method (GET POST)
          (path (subseq str (+ 2 (position #\space str)) (position #\space str :from-end t)))) ;path
    (print method) (print path)))

(defun create-http-header () 
    (return-from create-http-header "HTTP/1.1 200 ~%Content-Type: text/html;~2% "))

(defun get-packet-html () 
    (with-open-file (stream "packet.html" :direction :input) ;packet.htmlを読み込んで返す
        (let ((buf (make-string (file-length stream))))
            (read-sequence buf stream) (return-from get-packet-html buf))))

(defun packet-parser (packet) 
    (let ((json (make-string-output-stream))
            (header-length (subseq packet 1 2)))
        (princ "{" json)
        (princ "\"version\":\"" json)
        (princ (subseq packet 0 1) json)
        (princ "\"," json)
        (princ "\"header-length\":\"" json)
        (princ header-length json)
        (princ "\"," json)
        (princ "\"service\":\"" json)
        (princ (subseq packet 2 4) json)
        (princ "\"," json)
        (princ "\"packet-length\":\"" json)
        (princ (subseq packet 4 8) json)
        (princ "\"," json)
        (princ "\"identifier\":\"" json)
        (princ (subseq packet 8 12) json)
        (princ "\"," json)
        (princ "\"flag\":\"" json)
        (princ (subseq packet 12 16) json)
        (princ "\"," json)
        (princ "\"TTL\":\"" json)
        (princ (subseq packet 16 18) json)
        (princ "\"," json)
        (princ "\"protocol\":\"" json)
        (princ (subseq packet 18 20) json)
        (princ "\"," json)
        (princ "\"checksum\":\"" json)
        (princ (subseq packet 20 24) json)
        (princ "\"," json)
        (princ "\"source\":\"" json)
        (princ (convert-ip-format (subseq packet 24 32)) json)
        (princ "\"," json)
        (princ "\"destination\":\"" json)
        (princ (convert-ip-format (subseq packet 32 40)) json)
        (princ "\"," json)
        (princ "\"option\":\"" json)
        (let ((start (* (parse-integer header-length) 8)))
            (if (< 40 start) 
            (princ (subseq packet 40 start)  json))
            (princ "\"," json)
            (princ "\"body\":\"" json)
            (princ (subseq packet start)  json))
        (princ "\"" json)
        (princ "}" json)
        (return-from packet-parser (get-output-stream-string json))))

(defun convert-ip-format (raw-address) 
    (return-from convert-ip-format 
        (concatenate 'string (write-to-string (parse-integer (subseq raw-address 0 2) :radix 16)) 
                    "." 
                    (write-to-string (parse-integer (subseq raw-address 2 4) :radix 16)) 
                    "." 
                    (write-to-string (parse-integer (subseq raw-address 4 6) :radix 16)) 
                    "." 
                    (write-to-string (parse-integer (subseq raw-address 7 8) :radix 16)))))

;; (print (packet-parser "45000054C56C0000400133E9C0A80002C0A80001000092921E02000225C8C74C7251050008090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F303132333435363"))
(server)